export const STATUS_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'ChatGPT, API Platform, DALL-E, Sora',
    category: 'ai',
    pageUrl: 'https://status.openai.com',
    apiUrl: 'https://status.openai.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'openai.png',
  },
  {
    id: 'codex',
    name: 'Codex',
    description: 'OpenAI Codex & Code Generation Models',
    category: 'ai',
    pageUrl: 'https://status.openai.com',
    apiUrl: 'https://status.openai.com/api/v2/summary.json',
    adapter: 'openai-codex',
    logo: 'codex.png',
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Claude 3.5 Sonnet, Claude Pro & API Console',
    category: 'ai',
    pageUrl: 'https://status.anthropic.com',
    apiUrl: 'https://status.anthropic.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'claude.png',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Perplexity Search & API',
    category: 'ai',
    pageUrl: 'https://status.perplexity.com',
    apiUrl: 'https://status.perplexity.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'perplexity.png',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command, Embed, Rerank & Platform',
    category: 'ai',
    pageUrl: 'https://status.cohere.com',
    apiUrl: 'https://status.cohere.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cohere.png',
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud (Gemini & Vertex AI)',
    description: 'Gemini API, Vertex AI, and Google Cloud infrastructure',
    category: 'ai',
    pageUrl: 'https://status.cloud.google.com',
    apiUrl: 'https://status.cloud.google.com/incidents.json',
    adapter: 'gcp-json',
    logo: 'google.png',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Model Hub, Datasets, and Spaces',
    category: 'ai',
    pageUrl: 'https://status.huggingface.co',
    apiUrl: 'https://status.huggingface.co/badge',
    adapter: 'betterstack-badge',
    logo: 'huggingface.png',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Le Chat, La Plateforme & Model APIs',
    category: 'ai',
    pageUrl: 'https://status.mistral.ai',
    apiUrl: 'https://api.mistral.ai/v1/models',
    adapter: 'api-health',
    logo: 'mistral.png',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok & API Developer Platform',
    category: 'ai',
    pageUrl: 'https://status.x.ai',
    apiUrl: 'https://api.x.ai/v1/models',
    adapter: 'api-health',
    logo: 'xai.png',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Git, Actions, Packages, Copilot, and Webhooks',
    category: 'developer',
    pageUrl: 'https://www.githubstatus.com',
    apiUrl: 'https://www.githubstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'github.png',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'GitLab.com, CI/CD Shared Runners, and Registry',
    category: 'developer',
    pageUrl: 'https://status.gitlab.com',
    apiUrl: 'https://status.gitlab.com/1.0/status/5b36dc6502d06804c08349f7',
    adapter: 'statusio-json',
    logo: 'gitlab.png',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN, DNS, Cloudflare Workers & AI Gateway',
    category: 'developer',
    pageUrl: 'https://www.cloudflarestatus.com',
    apiUrl: 'https://www.cloudflarestatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cloudflare.png',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Frontend Cloud, Edge Network & AI SDK',
    category: 'developer',
    pageUrl: 'https://www.vercel-status.com',
    apiUrl: 'https://www.vercel-status.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'vercel.png',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Postgres Database, Auth, Storage & Realtime',
    category: 'developer',
    pageUrl: 'https://status.supabase.com',
    apiUrl: 'https://status.supabase.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'supabase.png',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Web Platform, Serverless & Edge Functions',
    category: 'developer',
    pageUrl: 'https://www.netlifystatus.com',
    apiUrl: 'https://www.netlifystatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'netlify.png',
  },
  {
    id: 'npm',
    name: 'npm',
    description: 'Node.js Package Registry and Website',
    category: 'developer',
    pageUrl: 'https://status.npmjs.org',
    apiUrl: 'https://status.npmjs.org/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'npm.png',
  },
  {
    id: 'docker',
    name: 'Docker Hub',
    description: 'Container Image Registry and Docker Build',
    category: 'developer',
    pageUrl: 'https://www.dockerstatus.com',
    apiUrl: 'https://www.dockerstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'docker.png',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment Processing API, Dashboard, and Webhooks',
    category: 'developer',
    pageUrl: 'https://status.stripe.com',
    apiUrl: 'https://status.stripe.com/current',
    adapter: 'stripe-json',
    logo: 'stripe.png',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'API, Bot Gateway, Voice, and Messaging',
    category: 'developer',
    pageUrl: 'https://discordstatus.com',
    apiUrl: 'https://discordstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'discord.png',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Workspace, Notion API, and Notion AI',
    category: 'developer',
    pageUrl: 'https://www.notion-status.com',
    apiUrl: 'https://www.notion-status.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'notion.png',
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Figma Design, FigJam, Plugins, and APIs',
    category: 'developer',
    pageUrl: 'https://status.figma.com',
    apiUrl: 'https://status.figma.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'figma.png',
  },
  {
    id: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services, Bedrock, and Cloud Health',
    category: 'developer',
    pageUrl: 'https://health.aws.amazon.com',
    apiUrl: 'https://status.aws.amazon.com/data.json',
    adapter: 'aws-json',
    logo: 'aws.png',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI Code Editor, Agents & Cursor API',
    category: 'ai',
    pageUrl: 'https://status.cursor.com',
    apiUrl: 'https://status.cursor.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cursor.png',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'GroqCloud Inference API & Console',
    category: 'ai',
    pageUrl: 'https://groqstatus.com',
    apiUrl: 'https://groqstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'groq.png',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text to Speech, Voice AI & Conversational Agents',
    category: 'ai',
    pageUrl: 'https://status.elevenlabs.io',
    apiUrl: 'https://status.elevenlabs.io/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'elevenlabs.png',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue Tracking, Projects & Linear API',
    category: 'developer',
    pageUrl: 'https://linearstatus.com',
    apiUrl: 'https://linearstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'linear.png',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error Monitoring, Performance & Session Replay',
    category: 'developer',
    pageUrl: 'https://status.sentry.io',
    apiUrl: 'https://status.sentry.io/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'sentry.png',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Monitoring, Logs, APM & Observability (US1)',
    category: 'developer',
    pageUrl: 'https://status.datadoghq.com',
    apiUrl: 'https://status.datadoghq.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'datadog.png',
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    description: 'CI/CD Pipelines, Runners & Orbs',
    category: 'developer',
    pageUrl: 'https://status.circleci.com',
    apiUrl: 'https://status.circleci.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'circleci.png',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Git Hosting, Pipelines & Pull Requests',
    category: 'developer',
    pageUrl: 'https://bitbucket.status.atlassian.com',
    apiUrl: 'https://bitbucket.status.atlassian.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'bitbucket.png',
  },
  {
    id: 'render',
    name: 'Render',
    description: 'Web Services, Static Sites & Managed Databases',
    category: 'developer',
    pageUrl: 'https://status.render.com',
    apiUrl: 'https://status.render.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'render.png',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    description: 'Droplets, Kubernetes, App Platform & Spaces',
    category: 'developer',
    pageUrl: 'https://status.digitalocean.com',
    apiUrl: 'https://status.digitalocean.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'digitalocean.png',
  },
  {
    id: 'mongodb',
    name: 'MongoDB Atlas',
    description: 'Atlas Database, Search & Data Services',
    category: 'developer',
    pageUrl: 'https://status.mongodb.com',
    apiUrl: 'https://status.mongodb.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'mongodb.png',
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Messaging, Voice, Video & SendGrid Email',
    category: 'developer',
    pageUrl: 'https://status.twilio.com',
    apiUrl: 'https://status.twilio.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'twilio.png',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Transactional Email API & Dashboard',
    category: 'developer',
    pageUrl: 'https://resend-status.com',
    apiUrl: 'https://resend-status.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'resend.png',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Storefront, Checkout, Admin & APIs',
    category: 'developer',
    pageUrl: 'https://www.shopifystatus.com',
    apiUrl: 'https://www.shopifystatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'shopify.png',
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: 'Vector Database, Inference & Assistant',
    category: 'ai',
    pageUrl: 'https://status.pinecone.io',
    apiUrl: 'https://status.pinecone.io/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'pinecone.png',
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    description: 'Speech-to-Text, Text-to-Speech & Voice Agent API',
    category: 'ai',
    pageUrl: 'https://status.deepgram.com',
    apiUrl: 'https://status.deepgram.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'deepgram.png',
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    description: 'Speech Recognition & Audio Intelligence API',
    category: 'ai',
    pageUrl: 'https://status.assemblyai.com',
    apiUrl: 'https://status.assemblyai.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'assemblyai.png',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast Inference & Fine-tuning Platform',
    category: 'ai',
    pageUrl: 'https://status.fireworks.ai',
    apiUrl: 'https://status.fireworks.ai/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'fireworks.png',
  },
  {
    id: 'lovable',
    name: 'Lovable',
    description: 'AI App Builder & Hosting',
    category: 'ai',
    pageUrl: 'https://status.lovable.dev',
    apiUrl: 'https://status.lovable.dev/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'lovable.png',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    description: 'AI Full-stack Web Development',
    category: 'ai',
    pageUrl: 'https://status.bolt.new',
    apiUrl: 'https://status.bolt.new/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'bolt.png',
  },
  {
    id: 'fly',
    name: 'Fly.io',
    description: 'App Hosting, Machines & Global Network',
    category: 'developer',
    pageUrl: 'https://status.flyio.net',
    apiUrl: 'https://status.flyio.net/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'fly.png',
  },
  {
    id: 'clerk',
    name: 'Clerk',
    description: 'Authentication & User Management',
    category: 'developer',
    pageUrl: 'https://status.clerk.com',
    apiUrl: 'https://status.clerk.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'clerk.png',
  },
  {
    id: 'upstash',
    name: 'Upstash',
    description: 'Serverless Redis, Kafka & QStash',
    category: 'developer',
    pageUrl: 'https://status.upstash.com',
    apiUrl: 'https://status.upstash.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'upstash.png',
  },
  {
    id: 'cockroach',
    name: 'CockroachDB Cloud',
    description: 'Distributed SQL Database',
    category: 'developer',
    pageUrl: 'https://status.cockroachlabs.cloud',
    apiUrl: 'https://status.cockroachlabs.cloud/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cockroach.png',
  },
  {
    id: 'grafana',
    name: 'Grafana Cloud',
    description: 'Dashboards, Metrics, Logs & Traces',
    category: 'developer',
    pageUrl: 'https://status.grafana.com',
    apiUrl: 'https://status.grafana.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'grafana.png',
  },
  {
    id: 'newrelic',
    name: 'New Relic',
    description: 'Observability, APM & Infrastructure Monitoring',
    category: 'developer',
    pageUrl: 'https://status.newrelic.com',
    apiUrl: 'https://status.newrelic.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'newrelic.png',
  },
  {
    id: 'snyk',
    name: 'Snyk',
    description: 'Security Scanning for Code & Dependencies',
    category: 'developer',
    pageUrl: 'https://status.snyk.io',
    apiUrl: 'https://status.snyk.io/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'snyk.png',
  },
  {
    id: 'launchdarkly',
    name: 'LaunchDarkly',
    description: 'Feature Flags & Experimentation',
    category: 'developer',
    pageUrl: 'https://status.launchdarkly.com',
    apiUrl: 'https://status.launchdarkly.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'launchdarkly.png',
  },
  {
    id: 'hashicorp',
    name: 'HashiCorp',
    description: 'Terraform Cloud, Vault & HCP Services',
    category: 'developer',
    pageUrl: 'https://status.hashicorp.com',
    apiUrl: 'https://status.hashicorp.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'hashicorp.png',
  },
  {
    id: 'postman',
    name: 'Postman',
    description: 'API Platform, Collections & Monitors',
    category: 'developer',
    pageUrl: 'https://status.postman.com',
    apiUrl: 'https://status.postman.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'postman.png',
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    description: 'Image & Video Management and Delivery',
    category: 'developer',
    pageUrl: 'https://status.cloudinary.com',
    apiUrl: 'https://status.cloudinary.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cloudinary.png',
  },
  {
    id: 'contentful',
    name: 'Contentful',
    description: 'Headless CMS & Content APIs',
    category: 'developer',
    pageUrl: 'https://www.contentfulstatus.com',
    apiUrl: 'https://www.contentfulstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'contentful.png',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    description: 'Visual Web Design, CMS & Hosting',
    category: 'developer',
    pageUrl: 'https://status.webflow.com',
    apiUrl: 'https://status.webflow.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'webflow.png',
  },
  {
    id: 'linode',
    name: 'Linode (Akamai)',
    description: 'Cloud Compute, Kubernetes & Object Storage',
    category: 'developer',
    pageUrl: 'https://status.linode.com',
    apiUrl: 'https://status.linode.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'linode.png',
  },
  {
    id: 'akamai',
    name: 'Akamai',
    description: 'CDN, Edge & Security Services',
    category: 'developer',
    pageUrl: 'https://www.akamaistatus.com',
    apiUrl: 'https://www.akamaistatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'akamai.png',
  },
  {
    id: 'pypi',
    name: 'PyPI',
    description: 'Python Package Index & Infrastructure',
    category: 'developer',
    pageUrl: 'https://status.python.org',
    apiUrl: 'https://status.python.org/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'pypi.png',
  },
  {
    id: 'rubygems',
    name: 'RubyGems',
    description: 'Ruby Package Registry & API',
    category: 'developer',
    pageUrl: 'https://status.rubygems.org',
    apiUrl: 'https://status.rubygems.org/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'rubygems.png',
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Issue & Project Tracking',
    category: 'developer',
    pageUrl: 'https://jira-software.status.atlassian.com',
    apiUrl: 'https://jira-software.status.atlassian.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'jira.png',
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Boards, Cards & Automation',
    category: 'developer',
    pageUrl: 'https://trello.status.atlassian.com',
    apiUrl: 'https://trello.status.atlassian.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'trello.png',
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product Analytics & Data Pipelines',
    category: 'developer',
    pageUrl: 'https://status.mixpanel.com',
    apiUrl: 'https://status.mixpanel.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'mixpanel.png',
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Customer Data Platform & Connections',
    category: 'developer',
    pageUrl: 'https://status.segment.com',
    apiUrl: 'https://status.segment.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'segment.png',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Data Cloud, Warehousing & Cortex AI',
    category: 'developer',
    pageUrl: 'https://status.snowflake.com',
    apiUrl: 'https://status.snowflake.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'snowflake.png',
  },
  {
    id: 'scaleway',
    name: 'Scaleway',
    description: 'Cloud Compute, Storage & Managed Services',
    category: 'developer',
    pageUrl: 'https://status.scaleway.com',
    apiUrl: 'https://status.scaleway.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'scaleway.png',
  },
  {
    id: 'jfrog',
    name: 'JFrog Cloud',
    description: 'Artifactory, Xray & Package Management',
    category: 'developer',
    pageUrl: 'https://status.jfrog.io',
    apiUrl: 'https://status.jfrog.io/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'jfrog.png',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Services' },
  { id: 'ai', label: 'Artificial Intelligence' },
  { id: 'developer', label: 'Development & Cloud' },
];
