/**
 * Configuration of services monitored by Status Check.
 * Each service includes a unique ID, category, official URLs, and the adapter type used.
 */
export const STATUS_PROVIDERS = [
  // --- Artificial Intelligence ---
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'ChatGPT, API Platform, DALL-E, Sora',
    category: 'ai',
    pageUrl: 'https://status.openai.com',
    apiUrl: 'https://status.openai.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'openai.png',
  },
  {
    id: 'codex',
    name: 'Codex',
    description: 'OpenAI Codex & Code Generation Models',
    category: 'ai',
    pageUrl: 'https://status.openai.com',
    apiUrl: 'https://status.openai.com/api/v2/summary.json',
    adapter: 'openai-codex',
    logo: 'codex.png',
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Claude 3.5 Sonnet, Claude Pro & API Console',
    category: 'ai',
    pageUrl: 'https://status.anthropic.com',
    apiUrl: 'https://status.anthropic.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'claude.png',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Perplexity Search & API',
    category: 'ai',
    pageUrl: 'https://status.perplexity.com',
    apiUrl: 'https://status.perplexity.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'perplexity.png',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command, Embed, Rerank & Platform',
    category: 'ai',
    pageUrl: 'https://status.cohere.com',
    apiUrl: 'https://status.cohere.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cohere.png',
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud (Gemini & Vertex AI)',
    description: 'Gemini API, Vertex AI, and Google Cloud infrastructure',
    category: 'ai',
    pageUrl: 'https://status.cloud.google.com',
    apiUrl: 'https://status.cloud.google.com/incidents.json',
    adapter: 'gcp-json',
    logo: 'google.png',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Model Hub, Datasets, and Spaces',
    category: 'ai',
    pageUrl: 'https://status.huggingface.co',
    apiUrl: 'https://status.huggingface.co/badge',
    adapter: 'betterstack-badge',
    logo: 'huggingface.png',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Le Chat, La Plateforme & Model APIs',
    category: 'ai',
    pageUrl: 'https://status.mistral.ai',
    apiUrl: 'https://status.mistral.ai',
    adapter: 'custom',
    logo: 'mistral.png',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok & API Developer Platform',
    category: 'ai',
    pageUrl: 'https://status.x.ai',
    apiUrl: 'https://status.x.ai',
    adapter: 'custom',
    logo: 'xai.png',
  },

  // --- Developer Platforms & Infrastructure ---
  {
    id: 'github',
    name: 'GitHub',
    description: 'Git, Actions, Packages, Copilot, and Webhooks',
    category: 'developer',
    pageUrl: 'https://www.githubstatus.com',
    apiUrl: 'https://www.githubstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'github.png',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'GitLab.com, CI/CD Shared Runners, and Registry',
    category: 'developer',
    pageUrl: 'https://status.gitlab.com',
    apiUrl: 'https://status.gitlab.com/1.0/status/5b36dc6502d06804c08349f7',
    adapter: 'statusio-json',
    logo: 'gitlab.png',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN, DNS, Cloudflare Workers & AI Gateway',
    category: 'developer',
    pageUrl: 'https://www.cloudflarestatus.com',
    apiUrl: 'https://www.cloudflarestatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'cloudflare.png',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Frontend Cloud, Edge Network & AI SDK',
    category: 'developer',
    pageUrl: 'https://www.vercel-status.com',
    apiUrl: 'https://www.vercel-status.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'vercel.png',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Postgres Database, Auth, Storage & Realtime',
    category: 'developer',
    pageUrl: 'https://status.supabase.com',
    apiUrl: 'https://status.supabase.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'supabase.png',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Web Platform, Serverless & Edge Functions',
    category: 'developer',
    pageUrl: 'https://www.netlifystatus.com',
    apiUrl: 'https://www.netlifystatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'netlify.png',
  },
  {
    id: 'npm',
    name: 'npm',
    description: 'Node.js Package Registry and Website',
    category: 'developer',
    pageUrl: 'https://status.npmjs.org',
    apiUrl: 'https://status.npmjs.org/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'npm.png',
  },
  {
    id: 'docker',
    name: 'Docker Hub',
    description: 'Container Image Registry and Docker Build',
    category: 'developer',
    pageUrl: 'https://www.dockerstatus.com',
    apiUrl: 'https://www.dockerstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'docker.png',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment Processing API, Dashboard, and Webhooks',
    category: 'developer',
    pageUrl: 'https://status.stripe.com',
    apiUrl: 'https://status.stripe.com/current',
    adapter: 'stripe-json',
    logo: 'stripe.png',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'API, Bot Gateway, Voice, and Messaging',
    category: 'developer',
    pageUrl: 'https://discordstatus.com',
    apiUrl: 'https://discordstatus.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'discord.png',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Workspace, Notion API, and Notion AI',
    category: 'developer',
    pageUrl: 'https://www.notion-status.com',
    apiUrl: 'https://www.notion-status.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'notion.png',
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Figma Design, FigJam, Plugins, and APIs',
    category: 'developer',
    pageUrl: 'https://status.figma.com',
    apiUrl: 'https://status.figma.com/api/v2/summary.json',
    adapter: 'statuspage',
    logo: 'figma.png',
  },
  {
    id: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services, Bedrock, and Cloud Health',
    category: 'developer',
    pageUrl: 'https://health.aws.amazon.com',
    apiUrl: 'https://status.aws.amazon.com/data.json',
    adapter: 'aws-json',
    logo: 'aws.png',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Services' },
  { id: 'ai', label: 'Artificial Intelligence' },
  { id: 'developer', label: 'Development & Cloud' },
];
